name: ChestShopSearch
version: ${project.version}
author: BlvckBytes
main: at.blvckbytes.chestshop_search.ChestShopSearchPlugin
api-version: 1.21
depend: [WorldGuard, ChestShop, ItemPredicateParser]
softdepend: [floodgate]
commands:
  shopsearch:
    description: 'Search through all known shops'
  shopsearchtoggle:
    description: 'Toggle whether your current region participates in the global search'
  shopoverview:
    description: 'Browse through shops grouped by their owners'
  shopsearchreload:
    description: 'Reload the configuration-file of this plugin'
    permission: 'chestshopsearch.reload'
permissions:
  chestshopsearch.return-items:
    description: 'Allows to undo transactions within a configurable time-window'
  chestshopsearch.toggle.bypass:
    description: 'Allows to bypass having to be the owner of a region to toggle advertising in the shop-search'
