name: ChestShopSearch
version: 0.1
author: BlvckBytes
main: at.blvckbytes.chestshop_search.ChestShopSearchPlugin
api-version: 1.21
depend: [WorldGuard, ChestShop, ItemPredicateParser]
softdepend: [floodgate]
commands:
  shopsearch:
    description: 'Search through all known shops'
  shopsearchtoggle:
    description: 'Toggle whether your current region participates in the global search'
  shopsearchlanguage:
    description: 'Choose a personal language for search-predicates'
  shopoverview:
    description: 'Browse through shops grouped by their owners'
  shopsearchreload:
    description: 'Reload the configuration-file of this plugin'
    permission: 'chestshopsearch.reload'